
name: Build Binaries

on: workflow_dispatch

jobs:
  build_macos:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build binaries
        run: misc/build_macos.sh

      - name: Check-in binaries
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -f addons/gdterm/bin/libgdterm.macos.template_debug.framework/libgdterm.macos.template_debug
          git add -f addons/gdterm/bin/libgdterm.macos.template_release.framework/libgdterm.macos.template_release
          git commit -m "new binaries commit"
          git push

  build_linux_win:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build binaries
        run: misc/build_binaries.sh

      - name: Check-in binaries
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -f addons/gdterm/bin/libgdterm.linux.template_debug.arm64.so
          git add -f addons/gdterm/bin/libgdterm.linux.template_debug.x86_64.so
          git add -f addons/gdterm/bin/libgdterm.linux.template_release.arm64.so
          git add -f addons/gdterm/bin/libgdterm.linux.template_release.x86_64.so
          git add -f addons/gdterm/bin/libgdterm.windows.template_debug.x86_64.dll
          git add -f addons/gdterm/bin/libgdterm.windows.template_release.x86_64.dll
          git commit -m "new binaries commit"
          git push

