
name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build binaries
        run: misc/build_binaries.sh

      - name: Check-in binaries
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -f addons/gdterm/bin/libgdterm.linux.template_debug.arm64.so
          git add -f addons/gdterm/bin/libgdterm.linux.template_debug.x86_64.so
          git add -f addons/gdterm/bin/libgdterm.linux.template_release.arm64.so
          git add -f addons/gdterm/bin/libgdterm.linux.template_release.x86_64.so
          git add -f addons/gdterm/bin/libgdterm.windows.template_debug.x86_64.dll
          git add -f addons/gdterm/bin/libgdterm.windows.template_release.x86_64.dll
          git commit -m "new binaries commit"
          git push

